version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
    commands:
      - echo "Installing dependencies ..."

  pre_build:
    commands:
      - echo "Restoring dependencies ..."
      - dotnet restore

  build:
    commands:
      - echo "Building the project ..."
      - dotnet build --configuration Release --no-restore

  post_build:
    commands:
      - echo "Build completed."