version: 0.2

phases:
    install:
        runtime-versions:
            dotnet: 8.0
        commands:
            - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 8.0
    pre_build:
        commands:
            - echo "Restoring dependencies ..."
    build:
        commands:
            - echo "Building the project ..."
            - dotnet restore ./Proyecto.csproj
            - dotnet build ./Proyecto.csproj
            - dotnet publish ./Proyecto.csproj -c Release -o ./target
    post_build:
        commands:
          - echo "Build completed."
artifacts:
  files:
    - target/**/*