version: 0.2

phases:
  install:
    commands:
      - echo "Instalando .NET 9 desde canal 9.0..."
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 9.0
      - export PATH="$HOME/.dotnet:$HOME/.dotnet/tools:$PATH"
      - dotnet --version
      - echo "Restaurando dependencias..."
      - dotnet restore
  build:
    commands:
      - echo "Compilando la aplicación..."
      - dotnet publish -c Release -o published_app

artifacts:
  files:
    - published_app/**/*